### ISSUE TITLE
(?, series, Doctor Who) does not come up with anything

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-Wikidata#92] opened 2015-02-22 08:41 UTC
Whereas is should return the list of episodes. eg. https://www.wikidata.org/wiki/Q2497678

http://askplatyp.us/?lang=en&q=%28%3F%2C+series%2C+Doctor+Who%29

**Comment by Tpt** [comment] 2015-03-03 08:18
The root cause of this issue is that MongoDB 2.4 is not able to use more than one index per query. This query should work well if we use MongoDB 2.6

**Comment by Tpt** [comment] 2015-03-13 07:03
I have deployed MongoDB 3. This issue is fixed now

**Closed by Tpt** 2015-03-13 07:03 UTC
Labels: bug
